
# settings for db connection
# for local deployment / if the service container is not in a docker network with the postgres_db service, this must be bridge0-IP or localhost.

# postgres db
DATABASE_URI: postgresql://yourcommonsuser:yourcommonspw@postgres_db:5432/db_commons


# postgres db test
DATABASE_URI_TEST: postgresql://testuser:testpw@salted_discoverandstore_testdb:5432/db_test


# crawling parameters
GOOGLE_N_RESULTS_REPORT: 1
GOOGLE_N_RESULTS_GOOGLE: 1


# vdpp mongodb uri
VDPP_MONGODB_URI: mongodb://vdppmongouser:password@<your-vdpp-ip-address>:27017/?authSource=admin&readPreference=primary&directConnection=true&ssl=false


