x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'



version: '3.7'

services:
  postgres_db:
    container_name: salted_commons_postgres_db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - salted_commons_postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      start_period: 10s
      interval: 60s
      timeout: 5s
      retries: 5    
  
  # http://localhost:5050/  with admin@admin.com & root + connection data see .env
  pgadmin:
    container_name: salted_commons_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
       - salted_commons_pgadmin_data:/root/.pgadmin  
    ports:
      - "${PGADMIN_PORT}:80"
  
  # following services are for vizualization / load monitoring
  loki:
    container_name: salted_commons_loki
    image: grafana/loki:2.4.2
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    volumes: 
      - ./etc/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./etc/loki/data:/data/loki
    ports:
      - "3100:3100"

  
  prometheus:
    container_name: salted_commons_prometheus
    image: prom/prometheus:v2.33.5
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    

  tempo:
    container_name: salted_commons_tempo
    image: grafana/tempo:1.3.2
    restart: unless-stopped
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "14250:14250"
    depends_on:
      - loki
    

  grafana:
    container_name: salted_commons_grafana
    image: grafana/grafana:8.4.3
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true" 



volumes:
  salted_commons_postgres_data:
  salted_commons_pgadmin_data:


  