x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'


version: '3.7'

networks:
  default:
    name: salted_commons_default
    external: true

services:
  salted_discoverandstore_service:
    container_name: salted_discoverandstore_service
    build: ./src 
    # since this is an endlessly running command the containers stays running
    # add --reload if needed for debugging
    command: [sh, -c, "cd /usr/src/ && ls -la && uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-config ./app/logs/log.ini"]
    restart: unless-stopped
    # volumes:
    #   - ./src/:/usr/src/ # for debugging
    ports:
      - "${SERVICE_PORT}:8000"  
    environment:
      - APP_NAME=salted_discoverandstore_service
      - SALTED_SEARCHENGINE_SERVICE=$SALTED_SEARCHENGINE_SERVICE
      - MQTT_ENABLED=$MQTT_ENABLED
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
    logging: *default-logging

  
  
  salted_discoverandstore_testdb:
    container_name: salted_discoverandstore_testdb
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB_TEST} -U ${POSTGRES_USER_TEST}" ]
      start_period: 10s
      interval: 60s
      timeout: 5s
      retries: 5
    
  

