x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'


version: '3.7'

networks:
  default:
    name: salted_commons_default
    external: true

services:
  salted_crawling_service:
    container_name: salted_crawling_service
    build: ./src 
    # since this is an endlessly running command the containers stays running 
    # add --reload if needed for debugging
    command: [sh, -c, "cd /usr/src/ && ls -la && uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-config ./app/logs/log.ini"]
    restart: unless-stopped
    # volumes:
    #   - ./src/:/usr/src/     # for debugging
    ports:
      - "${SERVICE_PORT}:8000"  
    environment:
      - APP_NAME=$APP_NAME
      - VDPP_MIDDLEWARE_API=$VDPP_MIDDLEWARE_API
      - SALTED_FILESERVER_SERVICE=$SALTED_FILESERVER_SERVICE
      - SALTED_FILESERVER_SERVICE_PUB_ADDR=$SALTED_FILESERVER_SERVICE_PUB_ADDR
      - SALTED_PUBLISH_SERVICE=$SALTED_PUBLISH_SERVICE
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
      - MQTT_ENABLED=$MQTT_ENABLED
      - RANDOM_SUBLIST_BROKER=$RANDOM_SUBLIST_BROKER
      - SALTED_SEARCHENGINE_SERVICE=$SALTED_SEARCHENGINE_SERVICE
    logging: *default-logging
    networks:
      - default



  
  
  

